# Translation system - 7 languages
import os
from defendr.constants import CONFIG_DIR

APP_LANGS = {
    "pt": {
        "DefendR - Advanced Protection": "DefendR - Protecao Avancada",
        "Dashboard": "Dashboard",
        "📊  Dashboard": "📊  Dashboard",
        "⚙  Process Monitor": "⚙  Monitor de Processos",
        "🔍  File Scanner": "🔍  Scanner de Arquivos",
        "🛡  Real-Time Protection": "🛡  Protecao em Tempo Real",
        "🔒  Firewall": "🔒  Firewall",
        "🌐  Network": "🌐  Rede",
        "📦  Quarantine": "📦  Quarentena",
        "🧰  Tools": "🧰  Ferramentas",
        "🔧  Settings": "🔧  Configuracoes",
        "▶ Start Real-Time Protection": "▶ Iniciar Protecao",
        "⏹ Stop Real-Time Protection": "⏹ Parar Protecao",
        "▶ Start Ransomware Detection": "▶ Iniciar Anti-Ransomware",
        "⏹ Stop Ransomware Detection": "⏹ Parar Anti-Ransomware",
        "▶ Start Webcam Monitor": "▶ Iniciar Webcam",
        "⏹ Stop Webcam Monitor": "⏹ Parar Webcam",
        "🔴 Block Webcam": "🔴 Bloquear Webcam",
        "🟢 Unblock Webcam": "🟢 Desbloquear Webcam",
        "Block": "Bloquear",
        "Unblock": "Desbloquear",
        "Check URL": "Verificar URL",
        "🛡 Enable Firewall": "🛡 Ativar Firewall",
        "Disable Firewall": "Desativar Firewall",
        "🔄 Flush Rules": "🔄 Limpar Regras",
        "Block Port": "Bloquear Porta",
        "Allow Port": "Liberar Porta",
        "🔄 Refresh Rules": "🔄 Atualizar Regras",
        "▶ Start": "▶ Iniciar",
        "⏹ Stop": "⏹ Parar",
        "🔍 ARP Scan Network": "🔍 Varredura ARP",
        "📡 Router Info": "📡 Info Roteador",
        "📡 Scan Router": "📡 Escanear Roteador",
        "▶ Start Continuous Monitor": "▶ Monitor Continuo",
        "⏹ Stop Monitoring": "⏹ Parar Monitor",
        "📂 Add Config": "📂 Adicionar Config",
        "▶ Connect": "▶ Conectar",
        "⏹ Disconnect": "⏹ Desconectar",
        "Reset to Default": "Restaurar Padrao",
        "🔒 Enable DNSSEC": "🔒 Ativar DNSSEC",
        "🔄 Refresh": "🔄 Atualizar",
        "🗑 Delete All": "🗑 Excluir Tudo",
        "📁 Select File & Run": "📁 Selecionar e Executar",
        "🔍 Run Rootkit Scan": "🔍 Escanear Rootkit",
        "🔓 Unlock Vault": "🔓 Destravar Cofre",
        "🔒 Lock": "🔒 Travar",
        "💾 Save Entry": "💾 Salvar",
        "➕ Add": "➕ Adicionar",
        "📁 Shred File": "📁 Destruir Arquivo",
        "📂 Shred Folder": "📂 Destruir Pasta",
        "🧹 Wipe Free Space": "🧹 Limpar Espaco Livre",
        "🧹 Run Cleanup": "🧹 Executar Limpeza",
        "👁 Preview Cleanup": "👁 Visualizar",
        "🔄 Check for Updates": "🔄 Verificar Atualizacoes",
        "📥 Install All Updates": "📥 Instalar Tudo",
        "🔍 Check for Updates": "🔍 Verificar Atualizacoes",
        "Enable Game Mode": "Ativar Game Mode",
        "Disable Game Mode": "Desativar Game Mode",
        "Open DefendR": "Abrir DefendR",
        "Quit": "Sair",
        "Game Mode": "Game Mode",
        "Protected by DefendR": "Protegido por DefendR",
        "No threats": "Nenhuma ameaca",
        "threat(s) found": "ameaca(s) encontrada(s)",
        "Run with sudo for full firewall and network monitoring.": "Execute com sudo para monitoramento completo de firewall e rede.",
        "Protecao continua ativa em segundo plano": "Protecao continua ativa em segundo plano",
        "DefendR": "DefendR",
        "Status: Stopped": "Status: Parado",
        "Status: Active": "Status: Ativo",
        "Dashboard": "Dashboard",
        "Scanner": "Scanner",
        "Real-Time": "Tempo Real",
        "Firewall": "Firewall",
        "Network": "Rede",
        "Processes": "Processos",
        "Quarantine": "Quarentena",
        "Tools": "Ferramentas",
        "Settings": "Configuracoes",
        "Account": "Conta",
        "HD Scan": "Scan HD",
        "👤  Account": "👤  Conta",
        "Login, register, and manage your DefendR account": "Login, registro e gerenciamento da sua conta DefendR",
        "Login": "Entrar",
        "Email:": "Email:",
        "Password:": "Senha:",
        "Register": "Registrar",
        "Username:": "Usuario:",
        "Create Account": "Criar Conta",
        "Account Info": "Informacoes da Conta",
        "🚪 Logout": "🚪 Sair",
        "Send Error Report": "Enviar Relatorio de Erro",
        "Type:": "Tipo:",
        "Message:": "Mensagem:",
        "Describe the issue...": "Descreva o problema...",
        "Send Report": "Enviar Relatorio",
        "Bug": "Bug",
        "Feature Request": "Solicitacao de Funcionalidade",
        "False Positive": "Falso Positivo",
        "Crash": "Crash",
        "Other": "Outro",
        "Fill all fields": "Preencha todos os campos",
        "You must be logged in": "Voce precisa estar logado",
        "Write a message": "Escreva uma mensagem",
        "Report sent!": "Relatorio enviado!",
        "Registered:": "Registrado em:",
        "Last seen:": "Ultima vez:",
        "PC Info": "Info do PC",
        "💿  HD Scanner": "💿  Scanner HD",
        "Scan your drives and get security recommendations": "Escaneie seus discos e obtenha recomendacoes de seguranca",
        "Click to scan your HD": "Clique para escanear seu HD",
        "Ready": "Pronto",
        "Risk": "Risco",
        "Path": "Caminho",
        "Reason": "Motivo",
        "Results": "Resultados",
        "Recommendations": "Recomendacoes",
        "Drives": "Unidades",
        "Scanning drives...": "Escaneando unidades...",
        "Scan complete: %d files": "Escaneamento completo: %d arquivos",
        "MALICIOUS": "MALICIOSO",
        "SUSPICIOUS": "SUSPEITO",
        "ALLOWED": "PERMITIDO",
        "SAFE": "SEGURO",
        "No threats found": "Nenhuma ameaca encontrada",
        "All files are clean": "Todos os arquivos estao limpos",
        "✅ %d clean files - no action needed": "✅ %d arquivos limpos - nenhuma acao necessaria",
        "🔴 %d malicious files found - quarantine them immediately": "🔴 %d arquivos maliciosos encontrados - coloque em quarentena imediatamente",
        "🟡 %d suspicious files - review manually": "🟡 %d arquivos suspeitos - revise manualmente",
        "🟢 Drive is clean - no security issues detected": "🟢 Unidade limpa - nenhum problema de seguranca detectado",
        "💾 Disk usage: check for large unused files in Settings > Cleanup": "💾 Uso do disco: verifique arquivos grandes nao usados em Configuracoes > Limpeza",
        "🔄 Signatures: keep DefendR updated for best detection": "🔄 Assinaturas: mantenha o DefendR atualizado para melhor deteccao",
        "📊 /mnt/defendr: %dGB / %dGB (%d%% used)": "📊 /mnt/defendr: %dGB / %dGB (%d%% usado)",
        "🔴 WARNING: Disk almost full - free up space": "🔴 AVISO: Disco quase cheio - libere espaco",
        "🟡 Disk usage above 75% - consider cleanup": "🟡 Uso do disco acima de 75% - considere limpeza",
        "Scan Level:": "Nivel de Escaneamento:",
        "Light (quick)": "Leve (rapido)",
        "Medium (balanced)": "Medio (balanceado)",
        "Heavy (deep)": "Pesado (profundo)",
        "File": "Arquivo",
        "Scan stopped": "Escaneamento interrompido",
        "nav_dashboard": "System overview and real-time protection status",
        "Protecao continua ativa em segundo plano": "Protecao continua ativa em segundo plano",
        "Initializing engine...": "Inicializando motor...",
        "Loading signatures...": "Carregando assinaturas...",
        "Starting modules...": "Iniciando modulos...",
        "Configuring firewall...": "Configurando firewall...",
        "Preparing interface...": "Preparando interface...",
        "Almost ready...": "Quase pronto...",
    },
    "en": {},
    "es": {
        "DefendR - Advanced Protection": "DefendR - Proteccion Avanzada",
        "📊  Dashboard": "📊  Panel",
        "🔍  File Scanner": "🔍  Escaner",
        "🛡  Real-Time Protection": "🛡  Proteccion en Tiempo Real",
        "🔒  Firewall": "🔒  Cortafuegos",
        "🌐  Network": "🌐  Red",
        "📦  Quarantine": "📦  Cuarentena",
        "🧰  Tools": "🧰  Herramientas",
        "🔧  Settings": "🔧  Ajustes",
        "▶ Start": "▶ Iniciar",
        "⏹ Stop": "⏹ Parar",
        "Block": "Bloquear",
        "Unblock": "Desbloquear",
        "Open DefendR": "Abrir DefendR",
        "Quit": "Salir",
    },
    "fr": {
        "DefendR - Advanced Protection": "DefendR - Protection Avancee",
        "📊  Dashboard": "📊  Tableau",
        "🔍  File Scanner": "🔍  Scanner",
        "🛡  Real-Time Protection": "🛡  Protection Temps Reel",
        "🔒  Firewall": "🔒  Pare-feu",
        "🌐  Network": "🌐  Reseau",
        "📦  Quarantine": "📦  Quarantaine",
        "🧰  Tools": "🧰  Outils",
        "🔧  Settings": "🔧  Parametres",
        "Block": "Bloquer",
        "Unblock": "Debloquer",
        "Open DefendR": "Ouvrir DefendR",
        "Quit": "Quitter",
    },
    "de": {
        "DefendR - Advanced Protection": "DefendR - Erweiterter Schutz",
        "📊  Dashboard": "📊  Ubersicht",
        "🔍  File Scanner": "🔍  Scanner",
        "🛡  Real-Time Protection": "🛡  Echtzeitschutz",
        "🔒  Firewall": "🔒  Firewall",
        "🌐  Network": "🌐  Netzwerk",
        "📦  Quarantine": "📦  Quarantane",
        "🧰  Tools": "🧰  Werkzeuge",
        "🔧  Settings": "🔧  Einstellungen",
        "Block": "Sperren",
        "Unblock": "Entsperren",
        "Open DefendR": "DefendR offnen",
        "Quit": "Beenden",
    },
    "it": {
        "DefendR - Advanced Protection": "DefendR - Protezione Avanzata",
        "📊  Dashboard": "📊  Dashboard",
        "🔍  File Scanner": "🔍  Scanner",
        "🛡  Real-Time Protection": "🛡  Protezione in Tempo Reale",
        "🔒  Firewall": "🔒  Firewall",
        "🌐  Network": "🌐  Rete",
        "📦  Quarantine": "📦  Quarantena",
        "🧰  Tools": "🧰  Strumenti",
        "🔧  Settings": "🔧  Impostazioni",
        "Block": "Blocca",
        "Unblock": "Sblocca",
        "Open DefendR": "Apri DefendR",
        "Quit": "Esci",
    },
    "ru": {
        "DefendR - Advanced Protection": "DefendR - Rasshirennaya zashchita",
        "📊  Dashboard": "📊  Panel",
        "🔍  File Scanner": "🔍  Skaner",
        "🛡  Real-Time Protection": "🛡  Zashchita v realnom vremeni",
        "🔒  Firewall": "🔒  Faivol",
        "🌐  Network": "🌐  Set",
        "📦  Quarantine": "📦  Karantin",
        "🧰  Tools": "🧰  Instrumenty",
        "🔧  Settings": "🔧  Nastroiki",
        "Block": "Blokirovat",
        "Unblock": "Razblokirovat",
        "Open DefendR": "Otkryt DefendR",
        "Quit": "Vyiti",
    },
}

def detect_app_lang():
    installed_file = os.path.join(CONFIG_DIR, "installed")
    if os.path.exists(installed_file):
        try:
            with open(installed_file) as f:
                for line in f:
                    if line.startswith("lang="):
                        code = line.strip().split("=", 1)[1]
                        if code in APP_LANGS: return code
        except Exception: pass
    lang = os.environ.get("LANG", "pt").split("_")[0]
    return lang if lang in APP_LANGS else "en"

CURRENT_LANG = detect_app_lang()


def _(text):
    return APP_LANGS.get(CURRENT_LANG, APP_LANGS["en"]).get(text, text)

def set_language(code):
    global CURRENT_LANG
    if code in APP_LANGS:
        CURRENT_LANG = code
        return True
    return False
